name: ar_kit
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  arcore_flutter_plugin:
    # git:
    #   url: https://github.com/Kareemayman-dotcom/arcore_flutter_plugin.git
    #   ref: master
    path: /Users/ruslantsitser/dev/projects/sandbox/arcore_flutter_plugin
  arkit_plugin:
    path: /Users/ruslantsitser/dev/projects/sandbox/arkit_flutter_plugin
  collection: ^1.18.0
  flutter:
    sdk: flutter
  flutter_archive: ^6.0.0
  http: ^1.2.1
  image: ^4.1.7
  logger: ^2.2.0
  path_provider: ^2.1.2
  vector_math: ^2.1.4

dev_dependencies:
  flutter_lints: ^3.0.2
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/objects/
    - assets/objects/textures/
